/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Universal-Document-Parser.h
 #	source generated by 4D Plugin Wizard
 #	Project : Universal Document Parser
 #	author : miyako
 #	2026/03/30
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H
#define PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H

#include "4DPluginAPI.h"
#include <string>
#include <sstream>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>

#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#pragma mark -

void Extract(PA_PluginParameters params);
void Split(PA_PluginParameters params);
void Embeddings(PA_PluginParameters params);
void Embeddings_Setup(PA_PluginParameters params);

#endif /* PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H */
