/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Universal-Document-Parser.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Universal Document Parser
 #	author : miyako
 #	2026/03/30
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Universal-Document-Parser.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Universal Document Parser
            
			case 1 :
				Extract(params);
				break;
			case 2 :
				Split(params);
				break;
			case 3 :
				Embeddings(params);
				break;
			case 4 :
				Embeddings_Setup(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark 4D.File

static bool _object_to_path(PA_ObjectRef f, std::string& path, int type) {
 
    if(f != NULL) {
        C_TEXT pp;
        pp.setUTF8String((const uint8_t *)"platformPath", 12);
        PA_Unistring PLATFORMPATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
        PA_VariableKind vk = PA_GetObjectPropertyType(f, &PLATFORMPATH);
        if(vk == eVK_Unistring) {
            PA_Variable p = PA_GetObjectProperty(f, &PLATFORMPATH);//PA_ClearVariable
            PA_Variable cbparams[2];
            cbparams[0] = PA_CreateVariable(eVK_Unistring);//PA_DisposeUnistring
            cbparams[1] = PA_CreateVariable(eVK_Longint);//PA_DisposeUnistring
            PA_Unistring platformPath = PA_GetStringVariable(p);
            PA_SetStringVariable(&cbparams[0], &platformPath);
            PA_SetLongintVariable(&cbparams[1], 1/*fk platform path*/);
            PA_Variable folder = PA_ExecuteCommandByID(type, cbparams, 2);
            PA_ClearVariable(&cbparams[0]);
            PA_ClearVariable(&cbparams[1]);
            PA_ClearVariable(&p);
            
#if VERSIONMAC
            pp.setUTF8String((const uint8_t *)"path", 4);
            PA_Unistring PATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
            PA_Variable _p = PA_GetObjectProperty(PA_GetObjectVariable(folder), &PATH);//PA_ClearVariable
            platformPath = PA_GetStringVariable(_p);
            PA_DisposeUnistring(&PATH);
            PA_ClearVariable(&_p);
#endif
            C_TEXT t;
            t.setUTF16String(&platformPath);
            CUTF8String u8;
            t.copyUTF8String(&u8);
            path = std::string((const char *)u8.c_str(), u8.size());
        }
        PA_DisposeUnistring(&PLATFORMPATH);
        return (vk == eVK_Unistring);
    }
    
    return false;
}

static bool file_object_to_data(PA_ObjectRef f, std::vector<uint8_t>& data) {
    
    if(f != NULL) {
        
        const int cmd_4D = 1709;
        PA_Variable prm_4D[1];
        PA_Variable _4D = PA_ExecuteCommandByID(cmd_4D, prm_4D, 0);
        
        const int cmd_OB_Get = 1224;
        PA_Variable prm_OB_Get[2];
        prm_OB_Get[0] = _4D;
        prm_OB_Get[1] = PA_CreateVariable(eVK_Unistring);
        C_TEXT pp;
        pp.setUTF8String((const uint8_t *)"Blob", 4);
        PA_Unistring BLOB = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());
        PA_SetStringVariable(&prm_OB_Get[1], &BLOB);//DO NOT call PA_DisposeUnistring
        PA_Variable _4D_Blob = PA_ExecuteCommandByID(cmd_OB_Get, prm_OB_Get, 2);
        PA_ClearVariable(&prm_OB_Get[1]);//BLOB belongs to variable. no need to dispose
        
        const int cmd_OB_Instance_of = 1731;
        PA_Variable prm_OB_Instance_of[2];
        prm_OB_Instance_of[0] = PA_CreateVariable(eVK_Object);
        prm_OB_Instance_of[1] = _4D_Blob;
        PA_SetObjectVariable(&prm_OB_Instance_of[0], f);
        PA_Variable status = PA_ExecuteCommandByID(cmd_OB_Instance_of, prm_OB_Instance_of, 2);
        bool isBlob = PA_GetBooleanVariable(status);
        if(isBlob) {

            pp.setUTF8String((const uint8_t *)"size", 4);
            PA_Unistring SIZE = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
            PA_Variable _s = PA_GetObjectProperty(f, &SIZE);
            PA_long32 size = PA_GetRealVariable(_s);
            PA_DisposeUnistring(&SIZE);
            PA_ClearVariable(&_s);
            
            PA_Variable blob = PA_CreateVariable(eVK_Blob);
            
            const int cmd_COPY_BLOB = 558;
            PA_Variable prm_COPY_BLOB[5];
            prm_COPY_BLOB[0] = prm_OB_Instance_of[0];
            prm_COPY_BLOB[1] = blob;
            prm_COPY_BLOB[2] = PA_CreateVariable(eVK_Longint);
            prm_COPY_BLOB[3] = PA_CreateVariable(eVK_Longint);
            prm_COPY_BLOB[4] = PA_CreateVariable(eVK_Longint);
            
            PA_SetLongintVariable(&prm_COPY_BLOB[2], 0);
            PA_SetLongintVariable(&prm_COPY_BLOB[3], 0);
            PA_SetLongintVariable(&prm_COPY_BLOB[4], size);
            
            PA_ExecuteCommandByID(cmd_COPY_BLOB, prm_COPY_BLOB, 5);
            
            data.resize(size);
            PA_GetBlobVariable(blob, &data[0]);

            PA_ClearVariable(&prm_COPY_BLOB[1]);//blob
            PA_ClearVariable(&prm_COPY_BLOB[2]);
            PA_ClearVariable(&prm_COPY_BLOB[3]);
            PA_ClearVariable(&prm_COPY_BLOB[4]);
        }
        
        PA_ClearVariable(&prm_OB_Instance_of[0]);
        return isBlob;
    }
    
    return false;
}

static bool file_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1566 /*4D.File*/);
}

static bool folder_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1567 /*4D.Folder*/);
}

#pragma mark -

void Extract(PA_PluginParameters params) {

    PA_ObjectRef returnValue = PA_CreateObject();
    ob_set_b(returnValue, L"success", false);
    
    input_type  it = (input_type) PA_GetLongParameter(params, 1);
    output_type ot = (output_type)PA_GetLongParameter(params, 2);
    std::string outPath;
    
    PA_ObjectRef document = PA_GetObjectParameter(params, 3);
    if (document) {
                
        std::vector<uint8_t>data;
        CUTF8String _password;
        std::string password;
        if(ob_get_s(document, L"password", &_password))
           password = (const char *)_password.c_str();
        
        int max_paragraph_length = 100;
        if(ob_is_defined(document, L"max_paragraph_length")) {
            int intValue = (int)ob_get_n(document, L"max_paragraph_length");
            if(intValue > 0) {
                max_paragraph_length = intValue;
            }
        }
        
        bool unique_values_only = false;
        if(ob_is_defined(document, L"unique_values_only")) {
            unique_values_only = ob_get_b(document, L"unique_values_only");
        }

        PA_ObjectRef file = ob_get_o(document, L"file");
        std::string path;
        if (file) {
            if (file_object_to_path(file, path)) {
                std::cerr << "path:" << path << std::endl;
                FILE *f = _fopen(path.c_str(), _rb);
                if(f) {
                    _fseek(f, 0, SEEK_END);
                    size_t len = (size_t)_ftell(f);
                    _fseek(f, 0, SEEK_SET);
                    data.resize(len);
                    fread(data.data(), 1, data.size(), f);
                    fclose(f);
                }
            }
            if (file_object_to_data(file, data)) {
                std::cerr << "data:" << data.size() << std::endl;
            }
            if(data.size()) {
                switch (it) {
                    case input_type_xlsx:
                    case input_type_docx:
                    case input_type_pptx:
                        opc_parse_data(data,
                                       returnValue,
                                       ot,
                                       max_paragraph_length,
                                       unique_values_only,
                                       password);
                        break;
                    default:
                        break;
                }
            }
        }
    }
    PA_ReturnObject(params, returnValue);
}

void Split(PA_PluginParameters params) {

}

void Embeddings(PA_PluginParameters params) {

}

void Embeddings_Setup(PA_PluginParameters params) {

}

