/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Universal-Document-Parser.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Universal Document Parser
 #	author : miyako
 #	2026/03/30
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Universal-Document-Parser.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Universal Document Parser
            
			case 1 :
				Extract(params);
				break;
			case 2 :
				Split(params);
				break;
			case 3 :
				Embeddings(params);
				break;
			case 4 :
				Embeddings_Setup(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Extract(PA_PluginParameters params) {

}

void Split(PA_PluginParameters params) {

}

void Embeddings(PA_PluginParameters params) {

}

void Embeddings_Setup(PA_PluginParameters params) {

}

